apiVersion: v1
kind: Service
metadata:
  name: node-test-infra
  namespace: default
spec:
  selector:
    app: node-test-infra
  type: LoadBalancer 
  ports:
  - name: node-test-infra
    protocol: TCP
    port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - port: 80
